name: Terraform
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
      - name: terraform-init
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      - run: |
         ls
         terraform init
        working-directory: github-actions/assignment
