name: Terraform
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: terraform-init
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      - run: |
         terraform init
         terraform plan 
        working-directory: assignment
