env:
 TF_LOG: INFO
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

name: Terraform
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: AWSVersion
        run: aws --version
      - name: terraform-init
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      - run: |
         terraform init
         terraform plan
         terraform apply --auto-approve
        working-directory: assignment
